name: Create Docker Hub Repository

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Name of the Docker repository to create'
        required: true
        default: 'my-new-repo'

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Docker Hub Repository
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        REPO_NAME=${{ github.event.inputs.repository_name }}
        echo "Creating Docker Hub repository: $REPO_NAME"
        
        # Create repository
        curl -X POST -H "Content-Type: application/json" \
             -H "Authorization: Bearer $DOCKER_TOKEN" \
             -d '{"name": "'"$REPO_NAME"'"}' \
             https://hub.docker.com/v2/repositories/
