name: Validate Helm Chart

on:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Helm Lint
      run: helm lint ./RBCharts

    - name: Helm Template
      run: helm template ./RBCharts --values ./RBCharts/values.yaml

    - name: Install kubeconform
      run: |
        wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
        tar -xzvf kubeconform-linux-amd64.tar.gz
        sudo mv kubeconform /usr/local/bin/kubeconform

    - name: Kubeconform Validation
      run: helm template ./RBCharts --values ./RBCharts/values.yaml | kubeconform

    - name: Install helm-unittest
      run: helm plugin install https://github.com/quintush/helm-unittest

    - name: Helm Unit Test
      run: helm unittest ./RBCharts
