name: Validate Helm Chart

on:
    workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Helm Lint
      run: helm lint ./RBCharts

    - name: Helm Template
      run: helm template ./RBCharts --values ./RBCharts/values.yaml
