name: CI/CD for Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Specify the JDK distribution
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

     # - name: Build with Maven
     #   run: mvn clean install

     # - name: Run Tests
     #   run: mvn test

    #   - name: Run Spring Boot Application
    #   run: mvn spring-boot:run

      #- name: Build with Maven
      #  run: mvn clean package

      - name: Build with Maven
        run: mvn package -DskipTests
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build Docker image
        run: |
          docker build -t . ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:latest
  
      #- name: Tag Docker image
      #  run: |
      #    docker tag my-spring-boot-app:latest ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-boot-app:latest