name: SonarQube Scan

on:
    workflow_dispatch:

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -sS http://localhost:9000/api/system/health | grep -o '\"status\":\"GREEN\"'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=6
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Wait for SonarQube to be ready
      run: |
        while ! curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"'; do
          echo "Waiting for SonarQube to be ready..."
          sleep 10
        done

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://localhost:9000
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my-spring-boot-app \
          -Dsonar.sources=src \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN
